server:
  port: 8090
spring:
  datasource:
    name: phoenix
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/phoenix_user?useUnicode=true&characterEncoding=utf8mb4&allowMultiQueries=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      username: phoenix_user
      password: phoenix_user
      auto-commit: true
      idle-timeout: 10000
      pool-name: PhoenixSecurity
      max-lifetime: 1800000
      connection-timeout: 11000
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    table: flyway_schema_history
    baseline-on-migrate: true
    clean-on-validation-error: false
rsa:
  key:
    pubkeyloc: "D:\rsa-pub.pub"
    prikeyloc: "D:\rsa-pri.key"
swagger:
  enable: true
logging:
  level:
    root: INFO